### PR TITLE
Update 07-Implement Azure Functions.md

### PR DESCRIPTION
**Pull request by ITBlandMCT**
Did not need escape before "&", sorry!

# Module: 02
### Task 2

Fixes stray "\\" .

Changes proposed in this pull request:

- Removed incorrect "\\" before "&name="

### CODE REVIEW

**Comment by polichtm** [comment]
updated

**Comment by ITBlandMCT** [comment]
Marcin, this was closed but not merged, my typo is still in the file.
Thx

**Comment by polichtm** [comment]
Hi Eric, 
apologies - taken care of
rgds
Marcin

**Comment by ITBlandMCT** [comment]
Oh, no worries, I was just embarrassed that I introduced that typo!
-Eric

**Comment by polichtm** [comment]
;)

**Pull request merged**
